package cl.ap.ssn.integraciones.enums;

import cl.ap.ssn.integraciones.exceptions.ConfiguracionInvalidaException;

/**
 * 
 * @author David
 *
 */
public enum CodigoIntegracionEnum {

	FULFILLMENT("FULFILLMENT"),
	IRS_RP("IRS/RP"),
	STOCK_ACTUALIZA("STOCK_ACTUALIZA"),
	GET_POST_ORDEN_DTE("GET_POST_ORDEN_DTE"),
	GET_TIENDAS("GET_TIENDAS"),
	GET_CANCELAR_ORD_SAP("GET_CANCELAR_ORD_SAP"),
	ORDEN_GUARDAR("ORDEN_GUARDAR"),
	GET_MODIFICA_NC_SAP("GET_MODIFICA_NC_SAP"),
	GET_POST_NC_MANUAL("GET_POST_NC_MANUAL"),
	ENVIO_MAIL_STOCKSEG("ENVIO_MAIL_STOCKSEG"),
	POST_PDF_DTE("POST_PDF_DTE"),
	ORDEN_UNICO("ORDEN_UNICO"),
	ORDEN_FULFILLMENT("ORDEN_FULFILLMENT"),
	GET_ETIQUETA("GET_ETIQUETA"),
	GET_BODEGA("GET_BODEGA"),
	POST_ORDEN_SAP("POST_ORDEN_SAP"),
	ENVIO_MAIL_NC("ENVIO_MAIL_NC"),
	GET_PAPERLESS_URL_NC("GET_PAPERLESS_URL_NC"),
	BBR_NC("BBR_NC"),
	CANCELAR_NC_SAP("CANCELAR_NC_SAP"),
	IRS_STOCK("IRS_STOCK"),
	GET_PAPERLESS_TIMBRE("GET_PAPERLESS_TIMBRE"),
	ORDEN_GRUPO_NEW("ORDEN_GRUPO_NEW"),
	GET_DTE_NC_RPROC("GET_DTE_NC_RPROC"),
	PUT_STOCK("PUT_STOCK"),
	CANCELAR_ORDEN("CANCELAR_ORDEN"),
	POST_NC_DTE("POST_NC_DTE"),
	GET_CANCELAR_NC_SAP("GET_CANCELAR_NC_SAP"),
	SOLICITAR_ETIQUETA("SOLICITAR_ETIQUETA"),
	GET_BASE64_NC("GET_BASE64_NC"),
	CERRAR_FULFILLMENT("CERRAR_FULFILLMENT"),
	GENERA_FULFILLMENT("GENERA_FULFILLMENT"),
	CREATE_DTE_MV("CREATE_DTE_MV"),
	CREATE_DTE_MV_("CREATE_DTE_MV "), // Tiene un espacio
	GET_URL_ORDENMV("GET_URL_ORDENMV"),
	SEND_ENVIO("SEND_ENVIO"),
	ORDEN_GRUPO("ORDEN_GRUPO"),
	MODIFICA_ORDEN_SAP("MODIFICA_ORDEN_SAP"),
	POST_NC_SAP("POST_NC_SAP"),
	GET_POST_NC_SAP("GET_POST_NC_SAP"),
	FACTURACION("FACTURACION"),
	PAPERLESS_TIMBRE("PAPERLESS_TIMBRE"),
	PUT_DTE("PUT_DTE"),
	POST_DTE_NC("POST_DTE_NC"),
	GET_MODIFICA_ORD_SAP("GET_MODIFICA_ORD_SAP"),
	GET_POST_NC_DTE("GET_POST_NC_DTE"),
	BASE64_NC("BASE64_NC"),
	POST_NC_MANUAL("POST_NC_MANUAL"),
	NC_IRS("NC_IRS"),
	GET_POST_DTE_NC("GET_POST_DTE_NC"),
	POST_DTE_PDF_NC("POST_DTE_PDF_NC"),
	ESTADO("ESTADO"),
	BBR("BBR"),
	ENVIO_MAIL("ENVIO_MAIL"),
	CREAR_DELIVERY("CREAR_DELIVERY"),
	CANCELAR_ORDEN_SAP("CANCELAR_ORDEN_SAP"),
	GET_POST_ORDEN_SAP("GET_POST_ORDEN_SAP"),
	PUT_DTE_CANAL("PUT_DTE_CANAL"),
	PAPERLESS_URL_NC("PAPERLESS_URL_NC"),
	POST_ACCESO_TK("POST_ACCESO_TK"),
	GET_ORDENESMV("GET_ORDENESMV"),
	POST_DTE_NC_RPROC("POST_DTE_NC_RPROC"),
	CREAR_BODEGA("CREAR_BODEGA"),
	OMS_PUT_ENVIO("OMS_PUT_ENVIO"),
	POST_ORDEN_DTE("POST_ORDEN_DTE"),
	MODIFICA_NC_SAP("MODIFICA_NC_SAP"),
	POST_ORDEN_SAP_REV("POST_ORDEN_SAP_REV"),
	POST_DTE("POST_DTE"),
	CREAR_DELIVERY_MV("CREAR_DELIVERY_MV"),
	GET_ENVIO("GET_ENVIO"),
	PAPERLESS_URL("PAPERLESS_URL"),
	GET_PAPERLESS_URL("GET_PAPERLESS_URL"),
	ENVIO_MAIL_DEVOL("ENVIO_MAIL_DEVOL"),
	POST_DTE_RPRC_PDF_NC("POST_DTE_RPRC_PDF_NC")
	;

	private String value;

	CodigoIntegracionEnum(String value) {
		this.value = value;
	}

	public String getValue() {
		return this.value;
	}

	public static CodigoIntegracionEnum findByValue(String value){
		for (CodigoIntegracionEnum v : values()) {
			if (v.getValue().equals(value)) {
				return v;
			}
		}
		throw new ConfiguracionInvalidaException(String.format("Canal incorrecto: %s", value));
	}

}
